AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WordBoostBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: word-boost
      AccessControl: Private

  WordBoostCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Word boost distribution
        DefaultRootObject: index.html
        Origins:
          - DomainName: word-boost.s3.ap-southeast-1.amazonaws.com
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt WordBoostOriginAccessControl.Id
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_200

  WordBoostOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
          Description: Word boost OAC
          Name: WordBoostOAC
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

  WordBoostBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WordBoostBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${WordBoostBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Join ['', ['arn:aws:cloudfront::', !Ref 'AWS::AccountId', ':distribution/', !Ref WordBoostCloudFrontDistribution]]

Outputs:
  WordBoostCloudFrontDistributionUrl:
    Value: !GetAtt WordBoostCloudFrontDistribution.DomainName
    Description: URL for the website hosted on the CloudFront distribution
