AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Word Boost

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java11
    Architectures:
      - x86_64
    Environment:
      Variables:
        PARAM1: VALUE
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
        WORDS_TABLE: !Ref WordsTable

Resources:
  AddWordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.functions.AddWord::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WordsTable
      Events:
        AddWord:
          Type: Api
          Properties:
            Path: /add
            Method: post
  AddWordsSentenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.functions.AddWordsSentence::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WordsTable
      Events:
        AddWord:
          Type: Api
          Properties:
            Path: /add-words-sentence
            Method: post
  GetWordsByUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Deprecated. This is a legacy function. GetWordsByUnitsFunction should be used as a replacement
      CodeUri: WordBoostFunctions
      Handler: wordboost.functions.GetWordsByUnit::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetWordsByUnit:
          Type: Api
          Properties:
            Path: /words
            Method: get
  GetWordsByUnitsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.functions.GetWordsByUnits::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetWordsByUnits:
          Type: Api
          Properties:
            Path: /words-by-units
            Method: post
  GetUnitsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Deprecated. This is a legacy function. GetUnitsAndCoursesFunction should be used as a replacement
      CodeUri: WordBoostFunctions
      Handler: wordboost.functions.GetUnits::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetUnits:
          Type: Api
          Properties:
            Path: /units
            Method: get
  GetUnitsAndCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.functions.GetUnitsAndCourses::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetUnitsAndCourses:
          Type: Api
          Properties:
            Path: /units-and-courses
            Method: get
  GetUnitsByCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Deprecated. GetUnitsAndCoursesFunction should be used as a replacement
      CodeUri: WordBoostFunctions
      Handler: wordboost.functions.GetUnitsByCourses::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetUnitsByCourses:
          Type: Api
          Properties:
            Path: /units-by-courses
            Method: get
  AddLessonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.functions.AddLesson::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LessonsTable
      Events:
        AddLesson:
          Type: Api
          Properties:
            Path: /add-lesson
            Method: post
  WordsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  LessonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Lesson
      AttributeDefinitions:
        - AttributeName: course
          AttributeType: S
        - AttributeName: unit
          AttributeType: S
      KeySchema:
        - AttributeName: course
          KeyType: HASH
        - AttributeName: unit
          KeyType: RANGE

Outputs:
  ApiUrl:
    Description: "API gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  AddWordApi:
    Description: "AddWord URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add/"
  AddWordFunction:
    Description: "AddWord ARN"
    Value: !GetAtt AddWordFunction.Arn
  AddWordFunctionIamRole:
    Description: "AddWord's implicit IAM role"
    Value: !GetAtt AddWordFunctionRole.Arn
