AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Word Boost

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java11
    Architectures:
      - x86_64
    Environment:
      Variables:
        PARAM1: VALUE
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
        WORDS_TABLE: !Ref WordsTable

Resources:
  AddWordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.AddWord::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WordsTable
      Events:
        AddWord:
          Type: Api
          Properties:
            Path: /add
            Method: post
  GetWordsByUnitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.GetWordsByUnit::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetWordsByUnit:
          Type: Api
          Properties:
            Path: /words
            Method: get
  GetUnitsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.GetUnits::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetUnits:
          Type: Api
          Properties:
            Path: /units
            Method: get
  GetCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.GetCourses::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetUnits:
          Type: Api
          Properties:
            Path: /courses
            Method: get
  GetUnitsByCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WordBoostFunctions
      Handler: wordboost.GetUnitsByCourses::handleRequest
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        GetUnits:
          Type: Api
          Properties:
            Path: /units-by-courses
            Method: get
  WordsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  ApiUrl:
    Description: "API gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  AddWordApi:
    Description: "AddWord URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add/"
  AddWordFunction:
    Description: "AddWord ARN"
    Value: !GetAtt AddWordFunction.Arn
  AddWordFunctionIamRole:
    Description: "AddWord's implicit IAM role"
    Value: !GetAtt AddWordFunctionRole.Arn
